"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.completed_checkpoint_statistics import CompletedCheckpointStatistics
from flink_client.model.failed_checkpoint_statistics import FailedCheckpointStatistics
from flink_client.model.pending_checkpoint_statistics import PendingCheckpointStatistics
from flink_client.model.task_checkpoint_statistics import TaskCheckpointStatistics
globals()['CompletedCheckpointStatistics'] = CompletedCheckpointStatistics
globals()['FailedCheckpointStatistics'] = FailedCheckpointStatistics
globals()['PendingCheckpointStatistics'] = PendingCheckpointStatistics
globals()['TaskCheckpointStatistics'] = TaskCheckpointStatistics
from flink_client.model.checkpoint_statistics import CheckpointStatistics


class TestCheckpointStatistics(unittest.TestCase):
    """CheckpointStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckpointStatistics(self):
        """Test CheckpointStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CheckpointStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
