"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.serialized_throwable import SerializedThrowable
globals()['SerializedThrowable'] = SerializedThrowable
from flink_client.model.asynchronous_operation_info import AsynchronousOperationInfo


class TestAsynchronousOperationInfo(unittest.TestCase):
    """AsynchronousOperationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAsynchronousOperationInfo(self):
        """Test AsynchronousOperationInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AsynchronousOperationInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
