"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.node import Node
globals()['Node'] = Node
from flink_client.model.job_vertex_flame_graph import JobVertexFlameGraph


class TestJobVertexFlameGraph(unittest.TestCase):
    """JobVertexFlameGraph unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobVertexFlameGraph(self):
        """Test JobVertexFlameGraph"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobVertexFlameGraph()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
