"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.task_executor_memory_configuration import TaskExecutorMemoryConfiguration


class TestTaskExecutorMemoryConfiguration(unittest.TestCase):
    """TaskExecutorMemoryConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskExecutorMemoryConfiguration(self):
        """Test TaskExecutorMemoryConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskExecutorMemoryConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
