"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.user_accumulator import UserAccumulator
globals()['UserAccumulator'] = UserAccumulator
from flink_client.model.subtask_execution_attempt_accumulators_info import SubtaskExecutionAttemptAccumulatorsInfo


class TestSubtaskExecutionAttemptAccumulatorsInfo(unittest.TestCase):
    """SubtaskExecutionAttemptAccumulatorsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubtaskExecutionAttemptAccumulatorsInfo(self):
        """Test SubtaskExecutionAttemptAccumulatorsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubtaskExecutionAttemptAccumulatorsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
