"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.cluster_configuration_info_entry import ClusterConfigurationInfoEntry
globals()['ClusterConfigurationInfoEntry'] = ClusterConfigurationInfoEntry
from flink_client.model.cluster_configuration_info import ClusterConfigurationInfo


class TestClusterConfigurationInfo(unittest.TestCase):
    """ClusterConfigurationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterConfigurationInfo(self):
        """Test ClusterConfigurationInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterConfigurationInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
