"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.io_metrics_info import IOMetricsInfo
globals()['IOMetricsInfo'] = IOMetricsInfo
from flink_client.model.subtask_execution_attempt_details_info import SubtaskExecutionAttemptDetailsInfo


class TestSubtaskExecutionAttemptDetailsInfo(unittest.TestCase):
    """SubtaskExecutionAttemptDetailsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubtaskExecutionAttemptDetailsInfo(self):
        """Test SubtaskExecutionAttemptDetailsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubtaskExecutionAttemptDetailsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
