"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.hardware_description import HardwareDescription
from flink_client.model.resource_id import ResourceID
from flink_client.model.resource_profile_info import ResourceProfileInfo
from flink_client.model.slot_info import SlotInfo
from flink_client.model.task_executor_memory_configuration import TaskExecutorMemoryConfiguration
from flink_client.model.task_manager_metrics_info import TaskManagerMetricsInfo
globals()['HardwareDescription'] = HardwareDescription
globals()['ResourceID'] = ResourceID
globals()['ResourceProfileInfo'] = ResourceProfileInfo
globals()['SlotInfo'] = SlotInfo
globals()['TaskExecutorMemoryConfiguration'] = TaskExecutorMemoryConfiguration
globals()['TaskManagerMetricsInfo'] = TaskManagerMetricsInfo
from flink_client.model.task_manager_details_info import TaskManagerDetailsInfo


class TestTaskManagerDetailsInfo(unittest.TestCase):
    """TaskManagerDetailsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskManagerDetailsInfo(self):
        """Test TaskManagerDetailsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskManagerDetailsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
