"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.job_vertex_id import JobVertexID
from flink_client.model.subtask_execution_attempt_details_info import SubtaskExecutionAttemptDetailsInfo
globals()['JobVertexID'] = JobVertexID
globals()['SubtaskExecutionAttemptDetailsInfo'] = SubtaskExecutionAttemptDetailsInfo
from flink_client.model.job_vertex_details_info import JobVertexDetailsInfo


class TestJobVertexDetailsInfo(unittest.TestCase):
    """JobVertexDetailsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobVertexDetailsInfo(self):
        """Test JobVertexDetailsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobVertexDetailsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
