"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.serialized_throwable import SerializedThrowable
globals()['SerializedThrowable'] = SerializedThrowable
from flink_client.model.savepoint_info import SavepointInfo


class TestSavepointInfo(unittest.TestCase):
    """SavepointInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSavepointInfo(self):
        """Test SavepointInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SavepointInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
