"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.trigger_id import TriggerId
globals()['TriggerId'] = TriggerId
from flink_client.model.trigger_response import TriggerResponse


class TestTriggerResponse(unittest.TestCase):
    """TriggerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTriggerResponse(self):
        """Test TriggerResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TriggerResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
