"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import flink_client
from flink_client.api.default_api import DefaultApi  # noqa: E501
from flink_client.api_client import ApiClient


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        configuration = flink_client.Configuration(
            host = "http://localhost:8084"
        )
        api_client = ApiClient(configuration=configuration)
        self.api = DefaultApi(api_client=api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_cluster_delete(self):
        """Test case for cluster_delete

        """
        pass

    def test_config_get(self):
        """Test case for config_get

        """
        pass

    def test_datasets_datasetid_delete(self):
        """Test case for datasets_datasetid_delete

        """
        pass

    def test_datasets_delete_triggerid_get(self):
        """Test case for datasets_delete_triggerid_get

        """
        pass

    def test_datasets_get(self):
        """Test case for datasets_get

        """
        pass

    def test_jars_get(self):
        """Test case for jars_get

        """
        pass


    def test_jars_jarid_delete(self):
        """Test case for jars_jarid_delete

        """
        pass

    def test_jars_jarid_plan_get(self):
        """Test case for jars_jarid_plan_get

        """
        pass

    def test_jars_jarid_plan_post(self):
        """Test case for jars_jarid_plan_post

        """
        pass

    def test_jars_jarid_run_post(self):
        """Test case for jars_jarid_run_post

        """
        pass

    def test_jars_upload_post(self):
        """Test case for jars_upload_post

        """
        pass

    def test_jobmanager_config_get(self):
        """Test case for jobmanager_config_get

        """
        pass

    def test_jobmanager_logs_get(self):
        """Test case for jobmanager_logs_get

        """
        pass

    def test_jobmanager_metrics_get(self):
        """Test case for jobmanager_metrics_get

        """
        pass

    def test_jobmanager_thread_dump_get(self):
        """Test case for jobmanager_thread_dump_get

        """
        pass

    def test_jobs_get(self):
        """Test case for jobs_get

        """
        pass

    def test_jobs_jobid_accumulators_get(self):
        """Test case for jobs_jobid_accumulators_get

        """
        pass

    def test_jobs_jobid_checkpoints_config_get(self):
        """Test case for jobs_jobid_checkpoints_config_get

        """
        pass

    def test_jobs_jobid_checkpoints_details_checkpointid_get(self):
        """Test case for jobs_jobid_checkpoints_details_checkpointid_get

        """
        pass

    def test_jobs_jobid_checkpoints_details_checkpointid_subtasks_vertexid_get(self):
        """Test case for jobs_jobid_checkpoints_details_checkpointid_subtasks_vertexid_get

        """
        pass

    def test_jobs_jobid_checkpoints_get(self):
        """Test case for jobs_jobid_checkpoints_get

        """
        pass

    def test_jobs_jobid_config_get(self):
        """Test case for jobs_jobid_config_get

        """
        pass

    def test_jobs_jobid_exceptions_get(self):
        """Test case for jobs_jobid_exceptions_get

        """
        pass

    def test_jobs_jobid_execution_result_get(self):
        """Test case for jobs_jobid_execution_result_get

        """
        pass

    def test_jobs_jobid_get(self):
        """Test case for jobs_jobid_get

        """
        pass

    def test_jobs_jobid_metrics_get(self):
        """Test case for jobs_jobid_metrics_get

        """
        pass

    def test_jobs_jobid_patch(self):
        """Test case for jobs_jobid_patch

        """
        pass

    def test_jobs_jobid_plan_get(self):
        """Test case for jobs_jobid_plan_get

        """
        pass

    def test_jobs_jobid_rescaling_patch(self):
        """Test case for jobs_jobid_rescaling_patch

        """
        pass

    def test_jobs_jobid_rescaling_triggerid_get(self):
        """Test case for jobs_jobid_rescaling_triggerid_get

        """
        pass

    def test_jobs_jobid_savepoints_post(self):
        """Test case for jobs_jobid_savepoints_post

        """
        pass

    def test_jobs_jobid_savepoints_triggerid_get(self):
        """Test case for jobs_jobid_savepoints_triggerid_get

        """
        pass

    def test_jobs_jobid_stop_post(self):
        """Test case for jobs_jobid_stop_post

        """
        pass

    def test_jobs_jobid_vertices_vertexid_accumulators_get(self):
        """Test case for jobs_jobid_vertices_vertexid_accumulators_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_backpressure_get(self):
        """Test case for jobs_jobid_vertices_vertexid_backpressure_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_flamegraph_get(self):
        """Test case for jobs_jobid_vertices_vertexid_flamegraph_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_get(self):
        """Test case for jobs_jobid_vertices_vertexid_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_metrics_get(self):
        """Test case for jobs_jobid_vertices_vertexid_metrics_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_subtasks_accumulators_get(self):
        """Test case for jobs_jobid_vertices_vertexid_subtasks_accumulators_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_subtasks_metrics_get(self):
        """Test case for jobs_jobid_vertices_vertexid_subtasks_metrics_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_subtasks_subtaskindex_attempts_attempt_accumulators_get(self):
        """Test case for jobs_jobid_vertices_vertexid_subtasks_subtaskindex_attempts_attempt_accumulators_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_subtasks_subtaskindex_attempts_attempt_get(self):
        """Test case for jobs_jobid_vertices_vertexid_subtasks_subtaskindex_attempts_attempt_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_subtasks_subtaskindex_get(self):
        """Test case for jobs_jobid_vertices_vertexid_subtasks_subtaskindex_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_subtasks_subtaskindex_metrics_get(self):
        """Test case for jobs_jobid_vertices_vertexid_subtasks_subtaskindex_metrics_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_subtasktimes_get(self):
        """Test case for jobs_jobid_vertices_vertexid_subtasktimes_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_taskmanagers_get(self):
        """Test case for jobs_jobid_vertices_vertexid_taskmanagers_get

        """
        pass

    def test_jobs_jobid_vertices_vertexid_watermarks_get(self):
        """Test case for jobs_jobid_vertices_vertexid_watermarks_get

        """
        pass

    def test_jobs_metrics_get(self):
        """Test case for jobs_metrics_get

        """
        pass

    def test_jobs_overview_get(self):
        """Test case for jobs_overview_get

        """
        pass

    def test_jobs_post(self):
        """Test case for jobs_post

        """
        pass

    def test_overview_get(self):
        """Test case for overview_get

        """
        pass

    def test_savepoint_disposal_post(self):
        """Test case for savepoint_disposal_post

        """
        pass

    def test_savepoint_disposal_triggerid_get(self):
        """Test case for savepoint_disposal_triggerid_get

        """
        pass

    def test_taskmanagers_get(self):
        """Test case for taskmanagers_get

        """
        pass

    def test_taskmanagers_metrics_get(self):
        """Test case for taskmanagers_metrics_get

        """
        pass

    def test_taskmanagers_taskmanagerid_get(self):
        """Test case for taskmanagers_taskmanagerid_get

        """
        pass

    def test_taskmanagers_taskmanagerid_logs_get(self):
        """Test case for taskmanagers_taskmanagerid_logs_get

        """
        pass

    def test_taskmanagers_taskmanagerid_metrics_get(self):
        """Test case for taskmanagers_taskmanagerid_metrics_get

        """
        pass

    def test_taskmanagers_taskmanagerid_thread_dump_get(self):
        """Test case for taskmanagers_taskmanagerid_thread_dump_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
