"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.job_details import JobDetails
globals()['JobDetails'] = JobDetails
from flink_client.model.multiple_jobs_details import MultipleJobsDetails


class TestMultipleJobsDetails(unittest.TestCase):
    """MultipleJobsDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultipleJobsDetails(self):
        """Test MultipleJobsDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultipleJobsDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
