"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.cluster_configuration_info_entry import ClusterConfigurationInfoEntry


class TestClusterConfigurationInfoEntry(unittest.TestCase):
    """ClusterConfigurationInfoEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterConfigurationInfoEntry(self):
        """Test ClusterConfigurationInfoEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterConfigurationInfoEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
