"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.trigger_id import TriggerId
globals()['TriggerId'] = TriggerId
from flink_client.model.savepoint_trigger_request_body import SavepointTriggerRequestBody


class TestSavepointTriggerRequestBody(unittest.TestCase):
    """SavepointTriggerRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSavepointTriggerRequestBody(self):
        """Test SavepointTriggerRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SavepointTriggerRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
