"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.checkpoint_alignment import CheckpointAlignment
from flink_client.model.checkpoint_duration import CheckpointDuration
from flink_client.model.stats_summary_dto import StatsSummaryDto
globals()['CheckpointAlignment'] = CheckpointAlignment
globals()['CheckpointDuration'] = CheckpointDuration
globals()['StatsSummaryDto'] = StatsSummaryDto
from flink_client.model.summary import Summary


class TestSummary(unittest.TestCase):
    """Summary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSummary(self):
        """Test Summary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Summary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
