"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.completed_checkpoint_statistics import CompletedCheckpointStatistics
from flink_client.model.failed_checkpoint_statistics import FailedCheckpointStatistics
from flink_client.model.restored_checkpoint_statistics import RestoredCheckpointStatistics
globals()['CompletedCheckpointStatistics'] = CompletedCheckpointStatistics
globals()['FailedCheckpointStatistics'] = FailedCheckpointStatistics
globals()['RestoredCheckpointStatistics'] = RestoredCheckpointStatistics
from flink_client.model.latest_checkpoints import LatestCheckpoints


class TestLatestCheckpoints(unittest.TestCase):
    """LatestCheckpoints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLatestCheckpoints(self):
        """Test LatestCheckpoints"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LatestCheckpoints()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
