"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.job_id import JobID
from flink_client.model.resource_profile_info import ResourceProfileInfo
globals()['JobID'] = JobID
globals()['ResourceProfileInfo'] = ResourceProfileInfo
from flink_client.model.slot_info import SlotInfo


class TestSlotInfo(unittest.TestCase):
    """SlotInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSlotInfo(self):
        """Test SlotInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SlotInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
