"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.jar_file_info import JarFileInfo
globals()['JarFileInfo'] = JarFileInfo
from flink_client.model.jar_list_info import JarListInfo


class TestJarListInfo(unittest.TestCase):
    """JarListInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJarListInfo(self):
        """Test JarListInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JarListInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
