"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.user_accumulator import UserAccumulator
globals()['UserAccumulator'] = UserAccumulator
from flink_client.model.job_vertex_accumulators_info import JobVertexAccumulatorsInfo


class TestJobVertexAccumulatorsInfo(unittest.TestCase):
    """JobVertexAccumulatorsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobVertexAccumulatorsInfo(self):
        """Test JobVertexAccumulatorsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobVertexAccumulatorsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
