"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.checkpoint_alignment import CheckpointAlignment
from flink_client.model.checkpoint_duration import CheckpointDuration
globals()['CheckpointAlignment'] = CheckpointAlignment
globals()['CheckpointDuration'] = CheckpointDuration
from flink_client.model.completed_subtask_checkpoint_statistics_all_of import CompletedSubtaskCheckpointStatisticsAllOf


class TestCompletedSubtaskCheckpointStatisticsAllOf(unittest.TestCase):
    """CompletedSubtaskCheckpointStatisticsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompletedSubtaskCheckpointStatisticsAllOf(self):
        """Test CompletedSubtaskCheckpointStatisticsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompletedSubtaskCheckpointStatisticsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
