"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.job_vertex_id import JobVertexID
from flink_client.model.subtask_accumulators_info import SubtaskAccumulatorsInfo
globals()['JobVertexID'] = JobVertexID
globals()['SubtaskAccumulatorsInfo'] = SubtaskAccumulatorsInfo
from flink_client.model.subtasks_all_accumulators_info import SubtasksAllAccumulatorsInfo


class TestSubtasksAllAccumulatorsInfo(unittest.TestCase):
    """SubtasksAllAccumulatorsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubtasksAllAccumulatorsInfo(self):
        """Test SubtasksAllAccumulatorsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubtasksAllAccumulatorsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
