"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.job_vertex_id import JobVertexID
from flink_client.model.task_managers_info import TaskManagersInfo
globals()['JobVertexID'] = JobVertexID
globals()['TaskManagersInfo'] = TaskManagersInfo
from flink_client.model.job_vertex_task_managers_info import JobVertexTaskManagersInfo


class TestJobVertexTaskManagersInfo(unittest.TestCase):
    """JobVertexTaskManagersInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobVertexTaskManagersInfo(self):
        """Test JobVertexTaskManagersInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobVertexTaskManagersInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
