"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.garbage_collector_info import GarbageCollectorInfo
globals()['GarbageCollectorInfo'] = GarbageCollectorInfo
from flink_client.model.task_manager_metrics_info import TaskManagerMetricsInfo


class TestTaskManagerMetricsInfo(unittest.TestCase):
    """TaskManagerMetricsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskManagerMetricsInfo(self):
        """Test TaskManagerMetricsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskManagerMetricsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
