"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.execution_exception_info import ExecutionExceptionInfo
from flink_client.model.job_exception_history import JobExceptionHistory
globals()['ExecutionExceptionInfo'] = ExecutionExceptionInfo
globals()['JobExceptionHistory'] = JobExceptionHistory
from flink_client.model.job_exceptions_info_with_history import JobExceptionsInfoWithHistory


class TestJobExceptionsInfoWithHistory(unittest.TestCase):
    """JobExceptionsInfoWithHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobExceptionsInfoWithHistory(self):
        """Test JobExceptionsInfoWithHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobExceptionsInfoWithHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
