"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.thread_info import ThreadInfo
globals()['ThreadInfo'] = ThreadInfo
from flink_client.model.thread_dump_info import ThreadDumpInfo


class TestThreadDumpInfo(unittest.TestCase):
    """ThreadDumpInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThreadDumpInfo(self):
        """Test ThreadDumpInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ThreadDumpInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
