"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.job_id import JobID
globals()['JobID'] = JobID
from flink_client.model.jar_plan_request_body import JarPlanRequestBody


class TestJarPlanRequestBody(unittest.TestCase):
    """JarPlanRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJarPlanRequestBody(self):
        """Test JarPlanRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JarPlanRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
