"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.completed_subtask_checkpoint_statistics import CompletedSubtaskCheckpointStatistics
from flink_client.model.pending_subtask_checkpoint_statistics import PendingSubtaskCheckpointStatistics
globals()['CompletedSubtaskCheckpointStatistics'] = CompletedSubtaskCheckpointStatistics
globals()['PendingSubtaskCheckpointStatistics'] = PendingSubtaskCheckpointStatistics
from flink_client.model.subtask_checkpoint_statistics import SubtaskCheckpointStatistics


class TestSubtaskCheckpointStatistics(unittest.TestCase):
    """SubtaskCheckpointStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubtaskCheckpointStatistics(self):
        """Test SubtaskCheckpointStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubtaskCheckpointStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
