"""
    Flink JobManager REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1/1.15-SNAPSHOT
    Contact: user@flink.apache.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flink_client
from flink_client.model.serialized_value_optional_failure_object import SerializedValueOptionalFailureObject


class TestSerializedValueOptionalFailureObject(unittest.TestCase):
    """SerializedValueOptionalFailureObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSerializedValueOptionalFailureObject(self):
        """Test SerializedValueOptionalFailureObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SerializedValueOptionalFailureObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
